name: unive_breastcancer_client
description: Client application for the breast cancer classifier made in Python with FastAPI.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Models
  json_annotation: ^4.8.1

  # API
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # Models
  json_serializable: ^6.7.0
  build_runner: ^2.4.5


flutter:
  uses-material-design: true
